[package]
name = "tonk-notation"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
lsp-types = { workspace = true }
saphyr = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
