//! In-process language server, exposed over HTTP.
//!
//! The carry asserted-notation language server lives inside this
//! service worker — same process as the dialog-db, so completion
//! providers (when we add them) can hit live data without crossing
//! a network boundary. Two HTTP routes adapt the server's
//! transport-agnostic message API to a fetch-based pipe:
//!
//! - `POST /api/lsp` — request/response. The body is a single
//!   JSON-RPC 2.0 message (no LSP `Content-Length` framing — that
//!   only matters for stdio transports). The response body is the
//!   matching JSON-RPC reply, or empty for notifications.
//!
//! - `GET /api/lsp/events` — `text/event-stream`. Server-initiated
//!   notifications (most importantly `textDocument/publishDiagnostics`)
//!   are pushed onto this stream as SSE messages. The browser
//!   client opens it once on connect and keeps it for the page
//!   lifetime.
//!
//! Why two routes instead of WebSocket: this worker doesn't have a
//! WebSocket server bound, and `EventSource` works through the SW's
//! fetch handler with no extra plumbing. We can swap in WebSocket /
//! `MessageChannel` later if push throughput becomes a concern.

use std::sync::Arc;

use axum::{
    Extension,
    body::{Body, Bytes},
    extract::Request,
    http::{StatusCode, header},
    response::{IntoResponse, Response},
    routing::{get, post},
};
use axum_wasm_macros::wasm_compat;
use futures_util::StreamExt as _;
use http_body_util::BodyExt as _;
use tokio::sync::{Mutex, broadcast};
// `wasm_compat` expands to code that uses `oneshot` by bare path
// on the wasm cfg; on native it isn't referenced. Import it
// unconditionally so both cfgs see the symbol.
#[allow(unused_imports)]
use tokio::sync::oneshot;
use tokio_stream::wrappers::BroadcastStream;
use tonk_common::log;
use tonk_language_server::Server;

/// Channel capacity for outbound LSP notifications.
///
/// Each event is at most a few hundred bytes (a `publishDiagnostics`
/// payload). The capacity sets an upper bound on how many events a
/// slow consumer can fall behind before we start dropping — once
/// every receiver is at the head, the buffer wraps. 256 is enough
/// for any realistic burst (a `didChange` produces exactly one
/// notification today; even rapid typing won't outrun the SSE
/// stream).
const OUTBOUND_BUFFER: usize = 256;

/// Hub shared across LSP routes. One instance per worker; lives as
/// long as the worker does. Added to the router as an `Extension`
/// rather than wedged into `AppState` so it stays orthogonal to
/// the rest of the app's state shape.
pub struct LspHub {
    /// The language server itself. Sequential — every request
    /// takes the lock for the duration of `handle_message`. That's
    /// fine in a single-threaded SW: there's no real parallelism
    /// to lose, and ordering matters for document state (a
    /// `didChange` mustn't interleave with a `diagnostic` request
    /// from the same client).
    server: Mutex<Server>,
    /// Broadcast channel for server-initiated notifications. Each
    /// SSE subscriber gets its own `Receiver`. Bytes are the
    /// already-serialized JSON-RPC notification payload (without
    /// the SSE `data:`/`\n\n` framing — that's added per-subscriber
    /// in the stream).
    outbound: broadcast::Sender<Bytes>,
}

impl LspHub {
    pub fn new() -> Arc<Self> {
        let (outbound, _drop) = broadcast::channel(OUTBOUND_BUFFER);
        Arc::new(Self {
            server: Mutex::new(Server::new()),
            outbound,
        })
    }

    /// Run an LSP message through the server and queue any
    /// resulting outbound notifications onto the broadcast.
    /// Returns the JSON-RPC response (for requests) or `None`
    /// (for notifications and unparseable messages).
    async fn dispatch(&self, raw: &[u8]) -> Option<Vec<u8>> {
        let mut server = self.server.lock().await;
        let reply = server.handle_message(raw);
        // Drain outbound *before* releasing the lock so notifications
        // generated by this message land on the channel in the order
        // the server produced them.
        for note in server.take_outbound() {
            let bytes = match serde_json::to_vec(&note) {
                Ok(v) => v,
                Err(err) => {
                    log!("[lsp] failed to serialize outbound notification: {err}");
                    continue;
                }
            };
            // `send` errors only when there are zero receivers —
            // not a problem, the next subscriber will get future
            // events. Drop the result.
            let _ = self.outbound.send(Bytes::from(bytes));
        }
        reply
    }
}

/// Mount the LSP routes onto an axum router.
pub fn lsp_router() -> axum::Router {
    let hub = LspHub::new();
    axum::Router::new()
        .route("/api/lsp", post(handle_post))
        .route("/api/lsp/events", get(handle_events))
        .layer(Extension(hub))
}

/// `POST /api/lsp` handler. Reads the entire request body as a
/// JSON-RPC message, dispatches it, and returns the reply (or an
/// empty 204 for notifications).
#[wasm_compat]
async fn handle_post(
    Extension(hub): Extension<Arc<LspHub>>,
    request: Request,
) -> Response {
    let bytes = match request.into_body().collect().await {
        Ok(collected) => collected.to_bytes(),
        Err(err) => {
            log!("[lsp] failed to read request body: {err}");
            return (StatusCode::BAD_REQUEST, "failed to read body").into_response();
        }
    };

    // Always respond `200 OK`, even when the message was a
    // notification (no JSON-RPC reply). LSP-over-HTTP isn't
    // standardized; using 204 would be cleaner semantically but
    // the SW's response adapter (`router::axum`) attaches a body
    // stream for every response and 204 forbids one — the browser
    // throws. Empty 200 body is the JSON-RPC "no reply" signal
    // anyway, so the client side reads it the same way.
    let body = hub.dispatch(&bytes).await.unwrap_or_default();
    Response::builder()
        .status(StatusCode::OK)
        .header(header::CONTENT_TYPE, "application/json")
        .body(Body::from(body))
        .unwrap()
}

/// `GET /api/lsp/events` handler. Subscribes a fresh receiver on
/// the broadcast and returns a `text/event-stream` response whose
/// body emits one SSE event per outbound notification.
///
/// SSE framing: `data: <json>\n\n`. The client side
/// (`@codemirror/lsp-client`'s transport adapter) parses these and
/// hands the JSON to its message dispatcher.
#[wasm_compat]
async fn handle_events(Extension(hub): Extension<Arc<LspHub>>) -> Response {
    let receiver = hub.outbound.subscribe();
    // `BroadcastStream` adapts the receiver into a `Stream`. Lagged
    // items surface as `Err(BroadcastStreamRecvError::Lagged(n))`
    // which we silently filter — a slow consumer just catches up
    // from the newest message; the next edit will refresh the
    // diagnostic state for any document the client cares about.
    let body_stream = BroadcastStream::new(receiver).filter_map(
        |result: Result<Bytes, _>| async move {
            let bytes = result.ok()?;
            let mut framed = Vec::with_capacity(bytes.len() + 8);
            framed.extend_from_slice(b"data: ");
            framed.extend_from_slice(&bytes);
            framed.extend_from_slice(b"\n\n");
            Some(Ok::<_, std::io::Error>(Bytes::from(framed)))
        },
    );

    Response::builder()
        .status(StatusCode::OK)
        .header(header::CONTENT_TYPE, "text/event-stream")
        .header(header::CACHE_CONTROL, "no-cache")
        // `keep-alive` is the default in HTTP/1.1; making it
        // explicit signals intent to long-poll for proxies that
        // might otherwise close the stream.
        .header("Connection", "keep-alive")
        .body(Body::from_stream(body_stream))
        .unwrap()
}
