#!/bin/sh
# Flatten the Web Awesome entry stylesheets into one committed file.
#
# The three hand-written stylesheet <link>s in index.html (webawesome.css,
# themes/default.css, color/palettes/shoelace.css) fan out through nested
# `@import url(...)` into ~29 separate render-blocking files, four levels
# deep. Each level is a serial network round trip before first paint —
# measured at ~0.8-1.2 s of the cold-load first paint on staging. Inlining
# every import at its position produces the identical cascade in ONE
# render-blocking request.
#
# The output (webawesome-flat.css) is COMMITTED, not built per-build: the
# vendored webawesome dir changes only on a vendor bump. Re-run this script
# after updating assets/webawesome and commit the result:
#
#   sh scripts/flatten-webawesome.sh
#
# Semantics preserved deliberately:
#   - Files imported more than once (layers.css, utilities/size.css, ...)
#     are inlined at EVERY import position, exactly as the browser applies
#     them. Duplicate `@layer` statements are harmless (first wins) and the
#     duplicated rule bodies are identical, so the cascade is unchanged.
#   - Entry order matches the original <link> order (cascade-significant).
#   - Only `@import url('...');` lines are recognized; any other @import
#     form fails the run rather than passing through half-flattened.
set -eu

STYLES_DIR="$(cd "$(dirname "$0")/../assets/webawesome/styles" && pwd)"
OUT="$STYLES_DIR/webawesome-flat.css"

# The entries, in the exact order the original <link> tags loaded them.
ENTRIES="webawesome.css themes/default.css color/palettes/shoelace.css"

FLATTEN_STACK=""

# Recursively inline `@import url(...)` lines of "$1" to stdout. The body
# runs in a subshell — `( )`, not `{ }` — so each recursion level gets its
# own copy of file/dir/spec AND of FLATTEN_STACK, which therefore behaves as
# a per-branch import stack for cycle detection with zero unwinding code.
flatten() (
    file=$1
    case ":$FLATTEN_STACK:" in
        *":$file:"*)
            echo "flatten-webawesome: import cycle at $file" >&2
            exit 1
            ;;
    esac
    FLATTEN_STACK="$FLATTEN_STACK:$file"
    dir=$(dirname "$file")

    while IFS= read -r line || [ -n "$line" ]; do
        case "$line" in
            "@import url("*");")
                spec=${line#"@import url("}
                spec=${spec%%")"*}
                spec=${spec#\'}
                spec=${spec%\'}
                spec=${spec#\"}
                spec=${spec%\"}
                [ -f "$dir/$spec" ] || {
                    echo "flatten-webawesome: $file imports missing $spec" >&2
                    exit 1
                }
                printf '/* >>> %s */\n' "$spec"
                flatten "$dir/$spec"
                ;;
            "@import"*)
                echo "flatten-webawesome: unrecognized @import in $file: $line" >&2
                exit 1
                ;;
            *)
                printf '%s\n' "$line"
                ;;
        esac
    done <"$file"
)

{
    printf '/* GENERATED by scripts/flatten-webawesome.sh — do not edit.\n'
    printf '   Inlines the @import graph of: %s\n' "$ENTRIES"
    printf '   Re-run the script after a webawesome vendor bump. */\n'
    for entry in $ENTRIES; do
        printf '\n/* ===== entry: %s ===== */\n' "$entry"
        flatten "$STYLES_DIR/$entry"
    done
} >"$OUT"

# A leftover local @import means a form the parser missed — refuse to ship it.
if grep -n '^@import' "$OUT"; then
    echo "flatten-webawesome: unflattened @import remains in output" >&2
    exit 1
fi

echo "flatten-webawesome: wrote $OUT ($(wc -c <"$OUT" | tr -d ' ') bytes)"
