packages:
  - packages/*
  - examples/demo
  - examples/demo/app
  - examples/berlin
  - examples/berlin/app

onlyBuiltDependencies:
  - '@clerk/shared'
  - browser-tabs-lock
  - cbor-extract
  - core-js
  - esbuild
  - keytar
  - wasm-pack
