name = "tonk-access-service"
main = "./result/tonk-access-service/worker/shim.mjs"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

routes = [{ pattern = "hub.tonk.xyz", custom_domain = true }]

[build]
command = "nix build .#tonk-cloudflare-artifacts"

[assets]
directory = "./result/tonk-ui"
not_found_handling = "single-page-application"
binding = "ASSETS"
run_worker_first = ["/@", "/@/*", "/ucan", "/ucan/*"]

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "tonk-spaces"

[vars]
R2_ACCOUNT_ID = "5f20ca8a0de0a5ac52a14fa8bf9c90db"
R2_BUCKET_NAME = "tonk-spaces"

[env.staging]
routes = [{ pattern = "staging.tonk.xyz", custom_domain = true }]

[[env.staging.r2_buckets]]
binding = "BUCKET"
bucket_name = "tonk-spaces-staging"

[env.staging.vars]
R2_ACCOUNT_ID = "5f20ca8a0de0a5ac52a14fa8bf9c90db"
R2_BUCKET_NAME = "tonk-spaces-staging"
