name = "tonk-account-service"
main = "./result/tonk-account-service/worker/shim.mjs"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

routes = [{ pattern = "accounts.tonk.xyz", custom_domain = true }]

[build]
command = "nix build .#tonk-cloudflare-artifacts"

[[d1_databases]]
binding = "DB"
database_name = "tonk-accounts"
database_id = "a0c6698d-25e6-414b-8986-4fbeb1b5f992"
migrations_dir = "rust/tonk-account-service/migrations"

[[r2_buckets]]
binding = "CHAINS"
bucket_name = "tonk-account-chains"

[vars]
EMAIL_FROM = "tonk <accounts@tonk.spot>"
