-- When the activation link was last emailed.
--
-- The resend command is effectively unauthenticated: the person waiting
-- for the mail cannot sign as the account they have not activated yet,
-- so the account is an argument rather than the subject. That is safe
-- because the mail only goes to the address already on the row, but it
-- would be a nuisance without a rate limit, and a limit needs something
-- to compare against.
--
-- Null for rows written before this, which reads as "never sent" and
-- allows one immediate resend.
ALTER TABLE customer ADD COLUMN activation_sent_at INTEGER;
