import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { toolDefinitions } from '../catalog.mjs';

const args = process.argv.slice(2);
const check = args.includes('--check');
const desktop = args.find(arg => arg !== '--check');
if (!desktop || args.length !== (check ? 2 : 1)) {
  console.error('Usage: node scripts/sync-desktop.mjs [--check] /path/to/tonk-town');
  process.exit(1);
}
const source = await readFile(new URL('../tools.json', import.meta.url));
const hash = createHash('sha256').update(source).digest('hex');
const json = JSON.stringify(Object.fromEntries(toolDefinitions.map(tool => [tool.name, tool])), null, 2);
const output = `// Generated by tonk/mcp/scripts/sync-desktop.mjs. Do not edit.
// tools.json SHA-256: ${hash}
import Foundation

public enum TonkToolCatalog {
  public static func definition(_ name: String) -> JSONValue {
    guard let tool = definitions[name] else {
      preconditionFailure("Unknown canonical Tonk tool: \\(name)")
    }
    return tool
  }

  private static let definitions: [String: JSONValue] = {
    // This literal is generated from validated JSON and checked before release.
    let data = Data(#"""
${json}
"""#.utf8)
    return try! JSONDecoder().decode([String: JSONValue].self, from: data)
  }()
}
`;
const target = resolve(desktop, 'Sources/HarnessCore/TonkToolCatalog.generated.swift');
if (check) {
  if (await readFile(target, 'utf8') !== output) {
    console.error('Tonk Town tool catalog is out of date. Run sync-desktop.mjs without --check.');
    process.exitCode = 1;
  }
} else {
  await writeFile(target, output);
  // Machine-local checkout selection; the desktop repository ignores this file.
  await writeFile(resolve(desktop, 'mcp/.canonical-root'), fileURLToPath(new URL('../', import.meta.url)) + '\n');
}
