#!/usr/bin/env python3
"""Split an exported onboarding snapshot into Welcome and optional demo content.

Run after export.py (and asset compression), passing the full JSON snapshot.
The committed partitions can also be regenerated by omitting that argument.
Image extraction needs B3SUM (default b3sum), emitting a hexadecimal BLAKE3 hash.
No binary image data is retained in either JSON partition.
"""
import base64
import collections
import json
import os
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
LIB = ROOT / 'rust/tonk-core/assets/library'
HERE = pathlib.Path(__file__).parent
ALPHABET = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz'

def b58encode(data):
    n = int.from_bytes(data, 'big')
    out = ''
    while n:
        n, r = divmod(n, 58)
        out = ALPHABET[r] + out
    return '1' * (len(data) - len(data.lstrip(b'\0'))) + out

def b58decode(value):
    n = 0
    for c in value:
        n = n * 58 + ALPHABET.index(c)
    return b'\0' * (len(value) - len(value.lstrip('1'))) + n.to_bytes((n.bit_length()+7)//8, 'big')

def write(path, value):
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + '\n')

def main():
    snapshot = json.loads(pathlib.Path(sys.argv[1]).read_text()) if len(sys.argv)>1 else json.loads((LIB/'onboarding.yaml').read_text())
    if len(sys.argv)==1 and (LIB/'onboarding-demos.yaml').exists():
        extra = json.loads((LIB/'onboarding-demos.yaml').read_text())
        snapshot['artifacts'] += extra['artifacts']
        snapshot['blobs'] += extra['blobs']
    media_path = LIB/'onboarding-media.json'
    media = json.loads(media_path.read_text()) if media_path.exists() else []
    for a in snapshot['artifacts']:
        if a['of']=='tonk:vault/welcome-page' and a['the']=='xyz.tonk.view/ui':
            def replace(match):
                img = match[0]
                data = base64.b64decode(re.search(r'data:image/webp;base64,([^"\s]+)', img)[1])
                tmp = LIB/'welcome-image.tmp'
                tmp.write_bytes(data)
                digest = bytes.fromhex(subprocess.check_output([os.environ.get('B3SUM','b3sum'), str(tmp)], text=True).split()[0])
                entity = 'blob:' + b58encode(digest)
                name = 'welcome-' + b58encode(digest) + '.webp'
                tmp.rename(LIB/name)
                media.append({'entity':entity, 'url':'/library/'+name})
                img = re.sub(r'src="data:image/webp;base64,[^"]+"', '', img)
                # The custom element retains the authored img, alt text, dimensions,
                # CSS classes and lazy decoding behavior.
                return '<welcome-image entity="'+entity+'" with={dom.host/with} style="display:contents">'+img+'</welcome-image>'
            a['is'] = re.sub(r'<img\b[^>]*data:image/webp;base64,[^>]*>', replace, a['is'])
        if a['of']=='id:vault/component/active' and a['the']=='xyz.tonk.component/module':
            source = (HERE/'deferred.js').read_text()
            original = a['is'].split('\n// Welcome deferred content\n')[0]
            # Await optional preparation before exposing a demo's editable content.
            needle = "      const display = this.querySelector('tonk-display');"
            guard = """      if (id && id !== 'did:key:z6MkAMKLz5uDbduG95r9rQriwRit6DE4MAbBSmWqpUz8PxWB' &&
          !globalThis.__welcomeDeferred?.ready) {
        globalThis.__welcomeDeferred?.prepare(root).then(() => {
          if (this.isConnected) this.apply();
        }).catch(() => {});
        return;
      }

"""
            original = original.replace(guard, '').replace(needle, guard+needle)
            a['is'] = original+'\n// Welcome deferred content\n'+source
    media = list({m['entity']:m for m in media}.values())
    for m in media:
        data = (LIB / m['url'].split('/')[-1]).read_bytes()
        assert data[12:16] == b'VP8L' and data[20] == 0x2f
        dimensions = int.from_bytes(data[21:25], 'little')
        m['width'] = (dimensions & 0x3fff) + 1
        m['height'] = ((dimensions >> 14) & 0x3fff) + 1
        for a in snapshot['artifacts']:
            if a['of']=='tonk:vault/welcome-page' and a['the']=='xyz.tonk.view/ui':
                pattern = r'(<welcome-image entity="'+re.escape(m['entity'])+r'"[^>]*><img)([^>]*)(>)'
                def size(match):
                    attrs = re.sub(r' (?:width|height)="[^"]*"', '', match[2])
                    return match[1]+f' width="{m["width"]}" height="{m["height"]}"'+attrs+match[3]
                a['is'] = re.sub(pattern, size, a['is'])

    write(media_path, media)
    # Media metadata is available with Welcome; bytes are independently deferred.
    pairs = {(a['the'],a['of']) for a in snapshot['artifacts']}
    for m in media:
        for attr,value in [('xyz.tonk.blob/content-type','string:image/webp'),('xyz.tonk.blob/name','string:Welcome illustration')]:
            if (attr,m['entity']) not in pairs:
                snapshot['artifacts'].append({'the':attr,'of':m['entity'],'is':value,'cause':None})

    snapshot['artifacts'].sort(key=lambda a:(a['of'],a['the'],a['is']))
    groups = collections.defaultdict(list)
    for a in snapshot['artifacts']:
        groups[a['of']].append(a)
    # Shell and standard Tonk vocabulary; Vault's commands, views and aliases.
    roots = {e for e in groups if (e.startswith(('tonk:', 'id:tonk:', 'id:vault/', 'id:workspace/')) and not e.startswith(('tonk:zork/', 'id:vault/component/')))}
    roots |= {'space:home', 'id:component', 'id:prose', 'id:view'}
    roots |= {e for e in groups if e.startswith('id:vault/') and '/component/' not in e}
    roots |= {'id:vault/component/'+n for n in ['00-lib','active','page-fonts','title','tree','welcome-how-to-tonk','welcome-soup']}
    roots |= {m['entity'] for m in media}
    # Sidebar pairs deliberately do not drag in each page's model/content.
    metadata = {id(a) for a in snapshot['artifacts'] if a['the'].startswith(('xyz.tonk.vault.node/', 'xyz.tonk.vault.page/', 'xyz.tonk.vault.config/')) or a['the'] in ('xyz.tonk.vault/title','xyz.tonk.vault.welcome-page/heading')}
    # Compiled rule sources carry CBOR text, including their full attribute and
    # concept references. Read those references as well as the explicit graph.
    texts = {}
    for e,rows in groups.items():
        texts[e] = '\n'.join(b58decode(a['is'][6:]).decode('utf8',errors='replace') if a['is'].startswith('bytes:') else a['is'] for a in rows)
        if e.startswith('rule:') and ('xyz.tonk.vault' in texts[e] or 'dom.event.detail/vault-' in texts[e]):
            roots.add(e)
    # Attribute schema entities are addressed separately from attribute names.
    attrs = collections.defaultdict(set)
    for a in snapshot['artifacts']:
        if a['the']=='db.attribute/id': attrs[a['is'][7:]].add(a['of'])
    aliases = {a['of'][3:]:a['is'][7:] for a in snapshot['artifacts'] if a['the']=='db.name/referent' and a['is'].startswith('entity:')}
    reverse = collections.defaultdict(list)
    for e, rows in groups.items():
        for a in rows:
            if a['the'] in ('db.name/referent','dialog.rule/induces','dialog.rule/conclusion') and a['is'].startswith('entity:'):
                reverse[a['is'][7:]].append(e)
    selected = set()
    pending = list(roots)
    while pending:
        e = pending.pop()
        if e in selected or e not in groups: continue
        selected.add(e)
        pending.extend(reverse[e])
        for a in groups[e]:
            if id(a) in metadata: continue
            if a['is'].startswith('entity:'):
                pending.append(a['is'][7:])
            if a['the'] in attrs: pending.extend(attrs[a['the']])
        text = texts[e]
        # Literal identities referenced by authored JS/markup and compiled rules.
        for ref in re.findall(r'(?:did:key:|concept:|tonk:|id:|the:|rule:)[A-Za-z0-9_:/.-]+',text):
            pending.append(ref)
        for attr,targets in attrs.items():
            if attr in text: pending.extend(targets)
        # Unqualified models and command names in markup.
        for name in re.findall(r'(?:model=|model="|concept=|concept=")([A-Za-z0-9_:/.-]+)',text):
            if name in aliases: pending.append(aliases[name]); pending.append('id:'+name)
    initial=[]; deferred=[]
    for a in snapshot['artifacts']:
        (initial if a['of'] in selected or id(a) in metadata else deferred).append(a)
    # Partition by (attribute, entity), never by individual cardinality-many value.
    assert not ({(a['the'],a['of']) for a in initial} & {(a['the'],a['of']) for a in deferred})
    for name,rows,blobs in [('onboarding.yaml',initial,[]),('onboarding-demos.yaml',deferred,snapshot['blobs'])]:
        rows.sort(key=lambda a:(a['of'],a['the'],a['is']))
        write(LIB/name,{'artifacts':rows,'blobs':blobs})
        print(name,len(rows),'artifacts', (LIB/name).stat().st_size,'bytes')

if __name__=='__main__': main()
