[package]
name = "tonk-worker"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[features]
integration-tests = []
web-integration-tests = []

[dependencies]
async-trait = { workspace = true }
axum = { workspace = true, features = ["json", "macros", "query"] }
base58 = { workspace = true }
base64 = { workspace = true }
axum-wasm-macros = { workspace = true }
console_error_panic_hook = { workspace = true }
dialog-common = { workspace = true }
dialog-artifacts = { workspace = true, features = ["webcrypto"] }
dialog-query = { workspace = true }
dialog-s3-credentials = { workspace = true, features = ["ucan"] }
dialog-storage = { workspace = true, features = ["ucan"] }
futures-util = { workspace = true }
js-sys = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonk-common = { workspace = true }
tonk-space = { workspace = true }
tower-service = { workspace = true }
ucan = { workspace = true }
url = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
wasm-streams = { workspace = true }
web-sys = { workspace = true, features = [
    "CryptoKey",
    "FetchEvent",
    "Headers",
    "Request",
    "RequestInit",
    "Response",
    "ResponseInit",
    "ServiceWorkerGlobalScope",
    "WorkerGlobalScope",
    "WorkerLocation",
] }
web-time = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
idb = "0.6"

[dev-dependencies]
anyhow = { workspace = true }
dialog-common = { workspace = true, features = ["helpers"] }
tower = { workspace = true }
wasm-bindgen-test = { workspace = true }

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
getrandom = { workspace = true, features = ["wasm_js"] }
