# Fly.io configuration for Tonk app
app = "my-world"
primary_region = "ord"

[build]

# Main HTTP service for the frontend app
[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

# Additional service for Tonk sync server
[[services]]
  internal_port = 7777
  protocol = "tcp"
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[env]
  NODE_ENV = "production"
  PORT = "7777"
