#!/usr/bin/env node
// Bundles `src-js/index.ts` (the <tonk-code> custom element) and
// per-language entry points into `assets/`.
//
// Output layout:
//   assets/tonk-code.js             — main bundle, registers the element
//   assets/tonk-code-lang-<id>.js   — one chunk per language pack,
//                                     loaded on demand via dynamic import
//
// The main bundle is fully self-contained for the element's core
// behavior (state, view, history, default keymap) — it doesn't
// touch any language pack until a `mode` attribute requests one.
// Each language entry point exports a default `LanguageSupport`
// instance and is loaded by the element with a relative URL
// (`./tonk-code-lang-yaml.js`), which means the consumer must
// serve all bundles from the same directory.
//
// Usage:
//   node scripts/build.mjs           # production build
//   node scripts/build.mjs --watch   # rebuild on file changes

import { build, context } from "esbuild";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { languages as catalog } from "@codemirror/language-data";
import { sourceFingerprint, SOURCE_FINGERPRINT_PREFIX } from "./source-fingerprint.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const outdir = resolve(root, "assets");
const genDir = resolve(root, "src-js/lang/generated");
mkdirSync(outdir, { recursive: true });
mkdirSync(genDir, { recursive: true });

// Custom dialects that ship as hand-written packs (no upstream
// language-data entry). `dialog-yaml` re-exports the YAML grammar today;
// its own chunk keeps the public id stable for later dialect decorations.
const customLanguages = [
  { id: "yaml", entry: "src-js/lang/yaml.ts" },
  { id: "dialog-yaml", entry: "src-js/lang/dialog-yaml.ts" },
];

// A stable, filesystem-safe chunk id for a catalog language name.
const chunkIdOf = (name) =>
  name
    .toLowerCase()
    .replace(/\+/g, "p")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

// Extract each catalog language's loader (package + support-call, or SQL
// dialect) straight from `@codemirror/language-data`'s source. Generating
// a DIRECT import of the one language package per chunk is essential:
// going through `desc.load()` would pull in language-data, whose ~140
// dynamic imports would drag every language's chunk into the graph, so a
// single ```python block would fetch the whole catalog. A direct import
// keeps each chunk to exactly its own grammar.
const require = createRequire(import.meta.url);
const languageDataSrc = readFileSync(
  require.resolve("@codemirror/language-data"),
  "utf8",
);
function extractLoaders() {
  const loaders = new Map(); // name -> { kind, pkg, expr } | { kind:"sql", dialect }
  for (const block of languageDataSrc.split("LanguageDescription.of(").slice(1)) {
    const name = (block.match(/name:\s*"([^"]+)"/) || [])[1];
    if (!name) continue;
    const load = block.match(/load\(\)\s*\{\s*return\s+([\s\S]*?);?\s*\}\s*\}\)/);
    if (!load) continue;
    const body = load[1].trim();
    const imp = body.match(/^import\((["'])(.+?)\1\)\.then\(\s*(\w+)\s*=>\s*([\s\S]+)\)$/);
    const sql = body.match(/^sql\((?:"([^"]*)")?\)$/);
    if (imp) loaders.set(name, { kind: "import", pkg: imp[2], expr: imp[4].trim() });
    else if (sql) loaders.set(name, { kind: "sql", dialect: sql[1] || null });
  }
  return loaders;
}
const loaders = extractLoaders();

// The source of a generated per-language chunk. Three loader shapes from
// language-data: a direct package import (`m.python()`), a legacy stream
// mode (`legacy(m.clojure)` — wrap the StreamParser in a StreamLanguage,
// language-data's own `legacy` helper), and a SQL dialect (`sql(Dialect)`).
function generatedChunk(loader) {
  const head = `// GENERATED by scripts/build.mjs — do not edit.\n`;
  if (loader.kind === "sql") {
    return (
      head +
      `import { sql${loader.dialect ? `, ${loader.dialect}` : ""} } from "@codemirror/lang-sql";\n` +
      `export default sql(${loader.dialect ? `{ dialect: ${loader.dialect} }` : ""});\n`
    );
  }
  const expr = loader.expr.replace(/(^|[^.\w])m\./g, "$1pack.");
  if (/(^|[^.\w])legacy\(/.test(loader.expr)) {
    return (
      head +
      `import { LanguageSupport, StreamLanguage } from "@codemirror/language";\n` +
      `import * as pack from ${JSON.stringify(loader.pkg)};\n` +
      `const legacy = (parser: Parameters<typeof StreamLanguage.define>[0]) =>\n` +
      `  new LanguageSupport(StreamLanguage.define(parser));\n` +
      `export default ${expr};\n`
    );
  }
  return (
    head +
    `import * as pack from ${JSON.stringify(loader.pkg)};\n` +
    `export default ${expr};\n`
  );
}

// Generate one entry module per catalog language, directly importing the
// resolved package (or the shared SQL pack for a dialect) and exporting
// its `LanguageSupport` as the default. Splitting (below) shares the
// CodeMirror-core modules across all chunks, preserving the single-type
// identity requirement.
const catalogChunks = new Map(); // chunkId -> entry path
const aliasMap = {}; // name/alias/extension (lower-case) -> chunkId
for (const desc of catalog) {
  const loader = loaders.get(desc.name);
  if (!loader) continue; // unparsed loader: skip (no chunk, no alias)
  const chunkId = chunkIdOf(desc.name);
  if (!catalogChunks.has(chunkId)) {
    const entryPath = resolve(genDir, `${chunkId}.ts`);
    writeFileSync(entryPath, generatedChunk(loader));
    catalogChunks.set(chunkId, entryPath);
  }
  const keys = [desc.name, ...desc.alias, ...desc.extensions];
  for (const key of keys) {
    const k = key.toLowerCase();
    if (!(k in aliasMap)) aliasMap[k] = chunkId;
  }
}
// Custom packs win their ids/aliases over any catalog collision.
for (const { id } of customLanguages) aliasMap[id] = id;

// The static alias table the element bundles (no fetch to resolve a
// `language` attribute to a chunk id).
writeFileSync(
  resolve(root, "src-js/lang/chunks.generated.ts"),
  `// GENERATED by scripts/build.mjs — do not edit.\n` +
    `// Maps every language name/alias/extension (lower-cased) to its built\n` +
    `// \`tonk-code-lang-<id>.js\` chunk id.\n` +
    `export const LANGUAGE_CHUNKS: Record<string, string> = ${JSON.stringify(
      aliasMap,
      Object.keys(aliasMap).sort(),
      2,
    )};\n`,
);

const entryPoints = {
  "tonk-code": resolve(root, "src-js/index.ts"),
};
for (const { id, entry } of customLanguages) {
  entryPoints[`tonk-code-lang-${id}`] = resolve(root, entry);
}
for (const [chunkId, entryPath] of catalogChunks) {
  entryPoints[`tonk-code-lang-${chunkId}`] = entryPath;
}

const artifactFingerprintPlugin = {
  name: "tonk-code-source-fingerprint",
  setup(build) {
    build.onEnd((result) => {
      if (result.errors.length > 0) return;
      const bundlePath = resolve(outdir, "tonk-code.js");
      const bundle = readFileSync(bundlePath, "utf8");
      const fingerprintBanner =
        `// ${SOURCE_FINGERPRINT_PREFIX}${sourceFingerprint(root)}`;
      writeFileSync(bundlePath, `${fingerprintBanner}\n${bundle}`);

      // The banner adds one generated line. Preserve source-map accuracy
      // instead of leaving every original mapping shifted down by one.
      const mapPath = `${bundlePath}.map`;
      const map = JSON.parse(readFileSync(mapPath, "utf8"));
      map.mappings = `;${map.mappings}`;
      writeFileSync(mapPath, JSON.stringify(map));
    });
  },
};

/** @type {import('esbuild').BuildOptions} */
const options = {
  entryPoints,
  outdir,
  bundle: true,
  format: "esm",
  target: ["es2022"],
  minify: true,
  sourcemap: true,
  // Splitting is required for *correctness*, not just size: the main
  // bundle and language packs share `@codemirror/state` (and friends),
  // and CodeMirror uses `instanceof` to validate `Extension` values
  // when reconfiguring. Two independent copies of `@codemirror/state`
  // — one inlined in the main bundle, one in a language chunk — make
  // those checks fail and the language pack is rejected with
  // "Unrecognized extension value in extension set".
  //
  // Splitting puts the shared CodeMirror modules in one chunk that
  // both entries import, so there's exactly one identity per type.
  // (Earlier we worried this broke style injection — that turned out
  // to be a separate issue caused by `<wa-page>`'s shadow root
  // capturing the rendered tree, since fixed by mounting the editor
  // inside our own shadow root.)
  splitting: true,
  external: [],
  logLevel: "info",
  // The checked-in main bundle is copied verbatim by tonk-ui. Stamp only that
  // stable entry: stamping every split chunk changes its content-addressed
  // name and leaves an unnecessary duplicate of the whole language graph.
  plugins: [artifactFingerprintPlugin],
};

const watch = process.argv.includes("--watch");

if (watch) {
  const ctx = await context(options);
  await ctx.watch();
  console.log("[tonk-code] watching…");
} else {
  await build(options);
}
