//! Launching a subshell whose prompt says which spot it is on.
//!
//! `tonk spot enter` exports `TONK_SPOT` and hands you a shell. The
//! variable is what every command resolves, but a variable is
//! invisible — so this module also puts the spot in the prompt,
//! which is the part you actually read before typing.
//!
//! # Why this is shell-specific
//!
//! A prompt cannot be set through the environment. Every shell's
//! startup files run *after* we spawn it and assign `PS1`/`PROMPT`
//! themselves, overwriting anything we passed in. The only way in
//! is to append after those files have run, and each shell offers a
//! different door:
//!
//! - **bash** — `--rcfile <file>`, which *replaces* `~/.bashrc`, so
//!   the file has to source it first.
//! - **zsh** — `ZDOTDIR`, which redirects the whole startup chain,
//!   so the temporary directory needs a `.zshenv` and a `.zshrc`
//!   that both hand back to the real ones.
//! - **fish** — `-C`, which runs a command after `config.fish`.
//!   The only one with a purpose-built hook.
//!
//! Anything else gets a plain shell and a printed hint. That is the
//! honest fallback: an unrecognized shell still *works*, it just
//! doesn't get a decorated prompt.
//!
//! # What this cannot do
//!
//! Prompt frameworks that rebuild the prompt on every command —
//! powerlevel10k, starship, most oh-my-zsh themes — overwrite the
//! prefix on their first redraw. There is no fix from out here;
//! they own the prompt by design. [`FRAMEWORK_HINT`] is the line to
//! show those users, and `TONK_NO_PROMPT=1` turns the whole
//! mechanism off for people who would rather wire it themselves.
//!
//! Every command also announces its spot on stderr, so the prompt
//! is a convenience on top of a guarantee, never the only signal.

use std::path::{Path, PathBuf};

/// Set to a non-empty value to skip prompt decoration entirely and
/// get a plain subshell. For people whose prompt is already
/// generated and who would rather read `TONK_SPOT` themselves.
pub const NO_PROMPT_ENV: &str = "TONK_NO_PROMPT";

/// What a user with a prompt framework needs to do instead. Printed
/// when we can't decorate, and worth showing in docs.
pub const FRAMEWORK_HINT: &str = "add $TONK_SPOT to your prompt to see it (prompt frameworks like \
     starship or powerlevel10k rebuild the prompt themselves)";

/// The shells we can decorate, plus everything else.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Shell {
    /// bash, via `--rcfile`.
    Bash,
    /// zsh, via `ZDOTDIR`.
    Zsh,
    /// fish, via `-C`.
    Fish,
    /// Anything we don't know how to decorate. Still launched.
    Other,
}

/// Classify by executable name, which is all `$SHELL` gives us.
/// Matches on the file stem so `/bin/bash`, `/usr/local/bin/bash`
/// and a `bash-5.2` build all land in the same place.
pub fn detect(shell_path: &str) -> Shell {
    let stem = Path::new(shell_path)
        .file_name()
        .map(|name| name.to_string_lossy().to_lowercase())
        .unwrap_or_default();
    let stem = stem.split('-').next().unwrap_or(&stem);
    match stem {
        "bash" => Shell::Bash,
        "zsh" => Shell::Zsh,
        "fish" => Shell::Fish,
        _ => Shell::Other,
    }
}

/// Everything needed to spawn the decorated shell: the arguments to
/// add, the environment to set, and a temporary directory to remove
/// once it exits.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Launch {
    /// Extra arguments, before any the caller adds.
    pub args: Vec<String>,
    /// Extra environment entries.
    pub env: Vec<(String, String)>,
    /// Scratch directory to delete after the shell exits, if any.
    pub scratch: Option<PathBuf>,
    /// True when the prompt was left alone and the caller should
    /// print [`FRAMEWORK_HINT`].
    pub plain: bool,
}

/// bash: `--rcfile` replaces `~/.bashrc` rather than adding to it,
/// so the generated file sources the real one first. Sourcing is
/// guarded on existence — a missing `~/.bashrc` is normal, not an
/// error to spew on startup.
///
/// `$TONK_SPOT` is single-quoted so it is expanded when the prompt
/// is *drawn*, not when it is assigned. The prompt therefore tracks
/// the variable: `export TONK_SPOT=other` inside the shell moves it,
/// and unsetting it empties the segment rather than leaving a stale
/// name on screen. A baked-in name would eventually lie.
fn bash_rc() -> String {
    "# Generated by `tonk spot enter`.\n\
     # The user's own configuration loads first: a failure in\n\
     # tonk's prompt layer must never cost them their shell.\n\
     if [ -f \"$HOME/.bashrc\" ]; then . \"$HOME/.bashrc\"; fi\n\
     # Single quotes: expanded per redraw, so the prompt follows\n\
     # TONK_SPOT instead of freezing its value from entry time.\n\
     PS1='${TONK_SPOT:+(tonk: ${TONK_SPOT}) }'\"$PS1\"\n"
        .to_string()
}

/// zsh reads `.zshenv` then `.zshrc` from `ZDOTDIR`, so pointing
/// `ZDOTDIR` at a scratch directory would silently drop *both* of
/// the user's files. Each generated file hands back to the real
/// one, and `.zshrc` restores `ZDOTDIR` so anything the session
/// starts later behaves normally.
///
/// zsh needs one extra step for a *dynamic* segment: parameter
/// expansion inside `PROMPT` only happens under `PROMPT_SUBST`.
/// Enabling it unconditionally would change how the user's own
/// prompt is interpreted — a literal `$` or backtick in their
/// theme would suddenly evaluate — so the option is only used when
/// it is already on (frameworks like oh-my-zsh set it). Otherwise
/// the segment is baked, which is correct for the overwhelmingly
/// common case of a shell that stays on the spot it entered.
fn zsh_files(label: &str) -> [(&'static str, String); 2] {
    let real = "\"${TONK_REAL_ZDOTDIR:-$HOME}\"";
    [
        (
            ".zshenv",
            format!(
                "# Generated by `tonk spot enter`.\n\
                 [ -f {real}/.zshenv ] && source {real}/.zshenv\n"
            ),
        ),
        (
            ".zshrc",
            format!(
                "# Generated by `tonk spot enter`.\n\
                 [ -f {real}/.zshrc ] && source {real}/.zshrc\n\
                 # Hand ZDOTDIR back, so shells started from here\n\
                 # read the real configuration directly.\n\
                 ZDOTDIR=${{TONK_REAL_ZDOTDIR:-$HOME}}\n\
                 # Follow TONK_SPOT live where the shell already\n\
                 # substitutes parameters in prompts; otherwise bake\n\
                 # the name rather than turn PROMPT_SUBST on under\n\
                 # someone else's theme.\n\
                 if [[ -o prompt_subst ]]; then\n\
                 \x20 PROMPT='${{TONK_SPOT:+(tonk: ${{TONK_SPOT}}) }}'$PROMPT\n\
                 else\n\
                 \x20 PROMPT='{prefix}'$PROMPT\n\
                 fi\n",
                prefix = format!("(tonk: {label}) ").replace('\'', "'\\''"),
            ),
        ),
    ]
}

/// fish runs `-C` after `config.fish`, so the original prompt
/// function is already defined and can simply be wrapped. A
/// function body is re-evaluated on every redraw, so reading
/// `$TONK_SPOT` inside it is dynamic for free — no shell option to
/// negotiate, unlike zsh.
fn fish_init() -> String {
    "functions -q fish_prompt; and functions --copy fish_prompt __tonk_inner_prompt; \
     and function fish_prompt; \
     test -n \"$TONK_SPOT\"; and printf '(tonk: %s) ' \"$TONK_SPOT\"; \
     __tonk_inner_prompt; end"
        .to_string()
}

/// Build the launch plan for `shell_path`, decorating the prompt
/// with `label` where we can.
///
/// `scratch_root` is where generated startup files go (the caller
/// passes the platform temp dir; tests pass their own). A failure
/// to write them is not fatal — the shell still launches, just
/// plain, because losing a prompt decoration is not a reason to
/// refuse someone a shell.
pub fn plan(shell_path: &str, label: &str, scratch_root: &Path, decorate: bool) -> Launch {
    if !decorate {
        return Launch {
            plain: true,
            ..Launch::default()
        };
    }
    match detect(shell_path) {
        Shell::Bash => match write_scratch(scratch_root, &[("rc", bash_rc())]) {
            Some(dir) => Launch {
                args: vec!["--rcfile".into(), dir.join("rc").display().to_string()],
                scratch: Some(dir),
                ..Launch::default()
            },
            None => plain(),
        },
        Shell::Zsh => {
            let files = zsh_files(label);
            match write_scratch(scratch_root, &files) {
                Some(dir) => {
                    let mut env = vec![("ZDOTDIR".to_string(), dir.display().to_string())];
                    // Remember where the real files live before we
                    // redirect, including a ZDOTDIR the user had
                    // already set themselves.
                    let real = std::env::var("ZDOTDIR")
                        .ok()
                        .filter(|value| !value.is_empty())
                        .or_else(|| dirs::home_dir().map(|home| home.display().to_string()));
                    if let Some(real) = real {
                        env.push(("TONK_REAL_ZDOTDIR".to_string(), real));
                    }
                    Launch {
                        env,
                        scratch: Some(dir),
                        ..Launch::default()
                    }
                }
                None => plain(),
            }
        }
        Shell::Fish => Launch {
            args: vec!["-C".into(), fish_init()],
            ..Launch::default()
        },
        Shell::Other => plain(),
    }
}

fn plain() -> Launch {
    Launch {
        plain: true,
        ..Launch::default()
    }
}

/// Write generated startup files into a fresh directory under
/// `root`. `None` on any I/O failure, which the caller reads as
/// "launch plain".
///
/// The directory name carries the pid so concurrent `spot enter`
/// calls never share one — two terminals entering different spots
/// at the same moment must not overwrite each other's prompt.
fn write_scratch(root: &Path, files: &[(&str, String)]) -> Option<PathBuf> {
    let dir = root.join(format!("tonk-enter-{}", std::process::id()));
    std::fs::create_dir_all(&dir).ok()?;
    for (name, body) in files {
        std::fs::write(dir.join(name), body).ok()?;
    }
    Some(dir)
}

/// Remove a scratch directory once the shell has exited. Failure is
/// ignored: a leftover file in the temp dir is not worth an error
/// on the way out of a session.
pub fn cleanup(scratch: Option<&Path>) {
    if let Some(dir) = scratch {
        let _ = std::fs::remove_dir_all(dir);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    mod detecting {
        use super::*;

        #[test]
        fn it_classifies_by_executable_name_whatever_the_path() {
            assert_eq!(detect("/bin/bash"), Shell::Bash);
            assert_eq!(detect("/usr/local/bin/zsh"), Shell::Zsh);
            assert_eq!(detect("/opt/homebrew/bin/fish"), Shell::Fish);
            // Versioned builds are the same shell.
            assert_eq!(detect("/usr/bin/bash-5.2"), Shell::Bash);
        }

        #[test]
        fn it_falls_back_for_anything_it_cannot_decorate() {
            for path in ["/bin/sh", "/usr/bin/nu", "/bin/ksh", ""] {
                assert_eq!(detect(path), Shell::Other, "{path}");
            }
        }
    }

    mod planning {
        use super::*;

        fn scratch() -> tempfile::TempDir {
            tempfile::tempdir().expect("tempdir")
        }

        #[test]
        fn it_points_bash_at_a_generated_rcfile_that_sources_the_real_one() {
            let tmp = scratch();
            let launch = plan("/bin/bash", "garden", tmp.path(), true);
            assert_eq!(launch.args[0], "--rcfile");
            assert!(!launch.plain);

            let body = std::fs::read_to_string(&launch.args[1]).expect("rcfile written");
            // The user's config must load before we touch PS1, or a
            // mistake here costs them their shell setup.
            let sources = body.find(".bashrc").expect("sources .bashrc");
            let assigns = body.find("PS1=").expect("sets PS1");
            assert!(sources < assigns, "{body}");
        }

        /// The segment has to be *read* at redraw, not frozen at
        /// entry: a `TONK_SPOT=other tonk …` one-off leaves the
        /// shell alone (so the prompt is right), but an `export`
        /// moves the session, and a frozen name would then lie.
        #[test]
        fn it_gives_bash_a_prompt_that_follows_the_variable() {
            let tmp = scratch();
            let launch = plan("/bin/bash", "garden", tmp.path(), true);
            let body = std::fs::read_to_string(&launch.args[1]).expect("rcfile");

            // Single-quoted, so bash expands it per redraw.
            assert!(
                body.contains("PS1='${TONK_SPOT:+(tonk: ${TONK_SPOT}) }'"),
                "{body}"
            );
            // And the name it was entered with is nowhere in the file.
            assert!(!body.contains("garden"), "{body}");
        }

        #[test]
        fn it_redirects_zsh_and_hands_both_startup_files_back() {
            let tmp = scratch();
            let launch = plan("/bin/zsh", "garden", tmp.path(), true);
            let zdotdir = launch
                .env
                .iter()
                .find(|(key, _)| key == "ZDOTDIR")
                .map(|(_, value)| value.clone())
                .expect("sets ZDOTDIR");

            // Both files zsh reads from ZDOTDIR must exist, or the
            // user's own .zshenv / .zshrc silently stop loading.
            let env_file =
                std::fs::read_to_string(Path::new(&zdotdir).join(".zshenv")).expect(".zshenv");
            let rc_file =
                std::fs::read_to_string(Path::new(&zdotdir).join(".zshrc")).expect(".zshrc");
            assert!(env_file.contains(".zshenv"), "{env_file}");
            assert!(rc_file.contains(".zshrc"), "{rc_file}");
            // And ZDOTDIR is handed back, so nothing started from
            // this shell inherits the redirect.
            assert!(
                rc_file.contains("ZDOTDIR=${TONK_REAL_ZDOTDIR:-$HOME}"),
                "{rc_file}"
            );
        }

        /// zsh only substitutes parameters in prompts under
        /// PROMPT_SUBST, and switching that on beneath someone
        /// else's theme could change how *their* prompt evaluates.
        /// So: dynamic when it's already on, baked otherwise —
        /// never turned on by us.
        #[test]
        fn it_offers_zsh_a_dynamic_prompt_only_where_prompt_subst_is_already_on() {
            let tmp = scratch();
            let launch = plan("/bin/zsh", "garden", tmp.path(), true);
            let zdotdir = launch
                .env
                .iter()
                .find(|(key, _)| key == "ZDOTDIR")
                .map(|(_, value)| value.clone())
                .expect("sets ZDOTDIR");
            let rc = std::fs::read_to_string(Path::new(&zdotdir).join(".zshrc")).expect(".zshrc");

            assert!(rc.contains("if [[ -o prompt_subst ]]"), "{rc}");
            assert!(rc.contains("${TONK_SPOT:+(tonk: ${TONK_SPOT}) }"), "{rc}");
            assert!(rc.contains("(tonk: garden) "), "baked fallback: {rc}");
            assert!(!rc.contains("setopt"), "never enables it for them: {rc}");
        }

        #[test]
        fn it_wraps_the_existing_fish_prompt_without_a_scratch_file() {
            let tmp = scratch();
            let launch = plan("/opt/homebrew/bin/fish", "garden", tmp.path(), true);
            assert_eq!(launch.args[0], "-C");
            assert!(
                launch.args[1].contains("__tonk_inner_prompt"),
                "{:?}",
                launch.args
            );
            // A fish prompt is a function, re-run per redraw, so
            // reading the variable inside it is dynamic for free.
            assert!(launch.args[1].contains("$TONK_SPOT"), "{:?}", launch.args);
            assert!(!launch.args[1].contains("garden"), "{:?}", launch.args);
            assert!(launch.scratch.is_none(), "fish needs no scratch file");
        }

        #[test]
        fn it_launches_plain_for_an_unknown_shell() {
            let tmp = scratch();
            let launch = plan("/bin/sh", "garden", tmp.path(), true);
            assert_eq!(
                launch,
                Launch {
                    plain: true,
                    ..Launch::default()
                }
            );
        }

        /// The opt-out has to beat detection, not sit behind it —
        /// someone who set it wants a plain shell even in bash.
        #[test]
        fn it_launches_plain_when_decoration_is_switched_off() {
            let tmp = scratch();
            let launch = plan("/bin/bash", "garden", tmp.path(), false);
            assert!(launch.plain);
            assert!(launch.args.is_empty());
            assert!(launch.scratch.is_none());
        }

        /// zsh's baked fallback is the one place a label is still
        /// interpolated into generated shell source. A spot *name*
        /// is a conservative slug, but the label for
        /// `tonk spot enter ./x` is a path, and a path can contain
        /// a quote — which must not break out of the assignment.
        #[test]
        fn it_escapes_a_quote_in_the_zsh_fallback_label() {
            let tmp = scratch();
            let launch = plan("/bin/zsh", "it's/here/.tonk", tmp.path(), true);
            let zdotdir = launch
                .env
                .iter()
                .find(|(key, _)| key == "ZDOTDIR")
                .map(|(_, value)| value.clone())
                .expect("sets ZDOTDIR");
            let rc = std::fs::read_to_string(Path::new(&zdotdir).join(".zshrc")).expect(".zshrc");

            // The POSIX close-escape-reopen form, inside the
            // single-quoted prompt string.
            assert!(rc.contains("'\\''"), "{rc}");
            // Exactly the two assignments the if/else generates —
            // a broken-out quote would produce more or fewer.
            assert_eq!(rc.matches("PROMPT=").count(), 2, "{rc}");
        }

        /// bash and fish read the variable instead of embedding the
        /// label, so neither can be broken by its contents at all.
        #[test]
        fn it_never_interpolates_the_label_for_bash_or_fish() {
            let tmp = scratch();
            let awkward = "it's/here/.tonk";

            let bash = plan("/bin/bash", awkward, tmp.path(), true);
            let body = std::fs::read_to_string(&bash.args[1]).expect("rcfile");
            assert!(!body.contains("it's"), "{body}");

            let fish = plan("/usr/bin/fish", awkward, tmp.path(), true);
            assert!(!fish.args[1].contains("it's"), "{:?}", fish.args);
        }
    }
}
