//! Built-in concept registry.
//!
//! Some concepts are not user-defined facts on the branch — they
//! describe the meta-schema itself ([`attribute`], [`concept`]) or
//! repository state written by the worker as native Rust types
//! ([`branch`], [`replica`], [`remote`], [`tracking-branch`]). The
//! resolution surface can't fetch them because nothing on the
//! branch tags them as concepts; instead the analyzer consults
//! this registry first and falls through to the live environment
//! only when no built-in matches.
//!
//! Built-ins win over branch-defined concepts of the same name.
//! In-document `concept!` definitions still win over built-ins
//! within their own document, so users can shadow a built-in
//! locally for testing.
//!
//! # Result type
//!
//! The registry stores [`crate::resolution::ConceptDefinition`] —
//! entity plus a durability-tagged descriptor. Every built-in is
//! durable.

use std::sync::OnceLock;

use dialog_artifacts::Entity;
use dialog_query::ConceptDescriptor as DialogConceptDescriptor;

use crate::concept::concept_of_concept_descriptor;
use crate::resolution::ConceptDefinition;
use crate::rule_query::rule_of_rule_descriptor;
use crate::{BranchQuery, RemoteQuery, ReplicaQuery, TrackingBranchQuery};
use tonk_core::claim::ConceptDescriptor;
use tonk_core::meta::{AnonymousAttributeQuery, NameQuery};

/// Look up a built-in concept by head-name as a durability-tagged
/// [`ConceptDefinition`]. Returns `None` for names that fall
/// through to the live environment. Built-ins are always durable.
pub fn lookup_concept(name: &str) -> Option<ConceptDefinition> {
    REGISTRY
        .get_or_init(build_registry)
        .iter()
        .find(|(key, _)| *key == name)
        .map(|(_, concept)| concept.clone())
}

/// Iterate every built-in concept as `(name, ConceptDefinition)`
/// pairs. Used by the concept-of-concept query path to surface
/// built-ins in a `concept:` query result.
pub fn concept_registry() -> &'static [(&'static str, ConceptDefinition)] {
    REGISTRY.get_or_init(build_registry).as_slice()
}

static REGISTRY: OnceLock<Vec<(&'static str, ConceptDefinition)>> = OnceLock::new();

fn build_registry() -> Vec<(&'static str, ConceptDefinition)> {
    vec![
        ("attribute", builtin::<AnonymousAttributeQuery>("attribute")),
        ("concept", concept_descriptor()),
        ("rule", rule_descriptor()),
        ("name", builtin::<NameQuery>("name")),
        ("branch", builtin::<BranchQuery>("branch")),
        ("replica", builtin::<ReplicaQuery>("replica")),
        ("remote", builtin::<RemoteQuery>("remote")),
        (
            "tracking-branch",
            builtin::<TrackingBranchQuery>("tracking-branch"),
        ),
    ]
}

/// Built-in `concept` view — the concept-of-concept descriptor.
///
/// Resolves to the sentinel descriptor whose `this()` triggers
/// dispatch to [`crate::concept::AnonymousConceptQuery`] in
/// [`crate::concept::QueryPlan::from`], so a `concept:` head at
/// query time enumerates *every* concept (built-in + branch) with
/// a synthesised `source` field.
///
/// Kept as a hand-built descriptor (rather than `derive(Concept)`)
/// because the concept-of-concept's `with:` is a dictionary — an
/// arbitrary map of names to attribute references — not a fixed
/// record of named fields. Rust struct derives can't express that
/// shape, so this one stays JSON.
fn concept_descriptor() -> ConceptDefinition {
    ConceptDefinition {
        entity: "db:concept"
            .parse()
            .expect("`db:concept` is a valid entity URI"),
        descriptor: ConceptDescriptor::Durable(concept_of_concept_descriptor().clone()),
    }
}

/// Built-in `rule` view — the rule-of-rule descriptor.
///
/// Resolves to the sentinel descriptor whose `this()` triggers
/// dispatch to [`crate::rule_query::AnonymousRuleQuery`] in
/// [`crate::concept::QueryPlan::from`], so a `rule:` head at
/// query time enumerates *every* installed inductive rule with a
/// synthesised `definition` field. The rule-side parallel of
/// [`concept_descriptor`].
///
/// Kept as a hand-built descriptor (rather than `derive(Concept)`)
/// for the same reason `concept_descriptor` is: its synthesised
/// fields have no fixed-record Rust shape the derive can express.
fn rule_descriptor() -> ConceptDefinition {
    ConceptDefinition {
        entity: "db:rule".parse().expect("`db:rule` is a valid entity URI"),
        descriptor: ConceptDescriptor::Durable(rule_of_rule_descriptor().clone()),
    }
}

/// Build a built-in [`ConceptDefinition`] from a
/// `#[derive(Concept)]` Rust type's `Query` newtype.
///
/// The `Query` type's `Default` impl is generated by the derive
/// and the `From<Query>` conversion drops values, so this is a
/// pure schema-only path. The descriptor's `this()` would be a
/// content-derived hash; built-ins instead live at the stable
/// `db:<name>` URI so the `db:` scheme protection covers them
/// and the row remains identifiable without knowing the hash.
fn builtin<Q>(name: &str) -> ConceptDefinition
where
    Q: Default,
    DialogConceptDescriptor: From<Q>,
{
    let entity: Entity = format!("db:{name}")
        .parse()
        .expect("`db:<builtin>` is a valid entity URI");
    ConceptDefinition {
        entity,
        descriptor: ConceptDescriptor::Durable(DialogConceptDescriptor::from(Q::default())),
    }
}
