use leptos::{ev::Event, prelude::*, task::spawn_local};
use tonk_invite::Invite;
use wasm_bindgen::JsCast;

use crate::{api, components::InviteSpace};

/// Modal dialog showing a freshly minted invite URL.
///
/// Mounted once at the launcher level. Visibility is driven by the
/// shared [`InviteSpace`] signal: the workspace top bar's
/// `<tonk-share>` control writes `Some(name)` (via the shell's
/// `tonk:share` window bridge) to open the dialog and trigger the
/// mint; the dialog clears the signal back to `None` on close.
///
/// Consumes [`api::create_invite`]'s tagged response — for now
/// only the URL is rendered, but the same component can branch
/// on `Open` vs `Scoped` later without touching call sites.
#[component]
pub fn TonkInviteDialog() -> impl IntoView {
    let invite_space = use_context::<InviteSpace>().expect("InviteSpace provided by TonkShell");

    // Lifecycle of the dialog's body: pre-mint, in-flight, the
    // resulting URL, or an error to surface in a callout. Reset
    // every time the dialog closes so reopening always mints
    // fresh — invites are short-lived shareables, not retained.
    let url = RwSignal::new(Option::<String>::None);
    let subject = RwSignal::new(Option::<String>::None);
    let error = RwSignal::new(Option::<String>::None);
    let loading = RwSignal::new(false);

    // Re-fire the mint request whenever `invite_space` flips to a
    // new `Some(...)`. The dialog itself is always mounted; the
    // signal is the open/close trigger.
    Effect::new(move |_| {
        let Some(name) = invite_space.get() else {
            url.set(None);
            subject.set(None);
            error.set(None);
            loading.set(false);
            return;
        };
        url.set(None);
        subject.set(None);
        error.set(None);
        loading.set(true);
        spawn_local(async move {
            // Stop if the user closed the dialog (cleared the
            // signal) before the request landed.
            if invite_space.get_untracked().as_deref() != Some(name.as_str()) {
                return;
            }
            match api::create_invite(&name, None).await {
                Ok(response) => {
                    if invite_space.get_untracked().as_deref() != Some(name.as_str()) {
                        return;
                    }
                    let invite_url = response.url().to_string();
                    // Re-parse the minted URL to extract the
                    // subject DID for the sigil. The mint
                    // endpoint already validated the invite, so
                    // a parse failure here is genuinely
                    // unexpected — surface it as a soft warning
                    // (no sigil) rather than blocking the URL.
                    if let Ok(invite) = Invite::parse_url(&invite_url).await {
                        subject.set(Some(invite.subject().to_string()));
                    }
                    url.set(Some(invite_url));
                    loading.set(false);
                }
                Err(e) => {
                    if invite_space.get_untracked().as_deref() != Some(name.as_str()) {
                        return;
                    }
                    error.set(Some(format!("{e}")));
                    loading.set(false);
                }
            }
        });
    });

    let on_after_hide = move |_: Event| {
        invite_space.set(None);
    };

    let on_close = move |_| {
        invite_space.set(None);
    };

    // Focus + select the URL input the moment the URL lands so
    // copy-via-keyboard "just works." WA's `<wa-input>` proxies
    // `focus()` and `select()` to the underlying native input,
    // but the custom element's TS interface isn't generated by
    // wasm-bindgen — we look it up by id and invoke via JS
    // reflection. Cheap, contained, no NodeRef typing dance.
    const URL_INPUT_ID: &str = "tonk-invite-url";
    Effect::new(move |_| {
        if url.get().is_none() {
            return;
        }
        let Some(host) = window()
            .document()
            .and_then(|d| d.get_element_by_id(URL_INPUT_ID))
        else {
            return;
        };
        let host: &wasm_bindgen::JsValue = host.unchecked_ref();
        use js_sys::Reflect;
        for method in ["focus", "select"] {
            if let Ok(f) = Reflect::get(host, &method.into())
                && let Some(f) = f.dyn_ref::<js_sys::Function>()
            {
                let _ = f.call0(host);
            }
        }
    });

    view! {
        <wa-dialog
            label="Share this repo."
            prop:open=move || invite_space.get().is_some()
            on:wa-after-hide=on_after_hide
        >
            <div class="invite-body">
                <tonk-sigil
                    class="invite-body-sigil"
                    value=move || subject.get().and_then(|s| tonk_sigil::did_sigil_value(&s))
                ></tonk-sigil>
                <div class="invite-body-stack wa-stack wa-gap-s">
                    <p class="invite-body-caption">"anyone with this link can join & edit"</p>
                    { move || if loading.get() {
                        Some(view! { <wa-spinner></wa-spinner> }.into_any())
                    } else if let Some(value) = url.get() {
                        let value_for_input = value.clone();
                        let value_for_copy = value.clone();
                        Some(view! {
                            <div class="invite-link">
                                <wa-input
                                    class="invite-link-input"
                                    id=URL_INPUT_ID
                                    name="invite-url"
                                    label="Invite link"
                                    readonly
                                    prop:value=move || value_for_input.clone()
                                ></wa-input>
                                <wa-copy-button
                                    class="invite-link-copy"
                                    value=value_for_copy
                                ></wa-copy-button>
                            </div>
                        }.into_any())
                    } else {
                        None
                    } }
                    { move || error.get().map(|message| view! {
                        <wa-callout variant="danger">
                            <wa-icon slot="icon" name="circle-exclamation"></wa-icon>
                            { message }
                        </wa-callout>
                    }) }
                </div>
            </div>
            <wa-button
                slot="footer"
                variant="neutral"
                appearance="plain"
                type="button"
                on:click=on_close
            >"Close"</wa-button>
        </wa-dialog>
    }
}
