[package]
name = "tonk-workspace"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Viewer workspace custom elements."
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  "cfg(dialog_test_native_integration)",
  "cfg(dialog_test_wasm_integration)",
  'cfg(feature, values("web-integration-tests"))',
] }
