name: Deploy

on:
  pull_request:
  push:
    branches: [stable]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    name: Cloudflare Artifacts
    steps:
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: mshick/add-pr-comment@v2
        if: github.event_name == 'pull_request'
        with:
          message: |
            Deploying Cloudflare artifacts...

      - name: Build assets
        run: |
          nix build --accept-flake-config .#tonk-cloudflare-artifacts

      - name: Deploy preview
        if: github.event_name == 'pull_request'
        id: deploy-preview
        working-directory: rust/tonk-access-service
        run: |
          {
            echo 'command-output<<EOF'
            nix --accept-flake-config develop .#ci --command wrangler versions upload --preview-alias pr-${{ github.event.pull_request.number }}
            echo EOF
          } >> "$GITHUB_OUTPUT"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Deploy production
        if: github.event_name == 'push' && github.ref == 'refs/heads/stable'
        working-directory: rust/tonk-access-service
        run: nix --accept-flake-config develop --command wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - uses: mshick/add-pr-comment@v2
        if: github.event_name == 'pull_request'
        with:
          message: |
            Wrangler output for this change:
            
            ${{ steps.deploy-preview.outputs.command-output }}
            
